
server:
  port: 8080
  
  
#  servlet:
#    context-path: /surebank/api
  
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/surebankdb
    username: surebank_user
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
logging:
  file:
    name: log/surebank.log
  pattern:
   file: "%d %-5level [%thread] %logger:%msg%n"
   
surebank:
  app:
    jwtSecret: surebank@@12
    jwtExpirationMs: 86400000
    
info:
 application:
   name: SUREBANK APP
   description: It is Surebank Web Application developed by SUREBANK Dev. Team
   version: '@project.version@'  
    
   