server:
  port: 8080
#  servlet:
#    context-path: /bremenbank/api
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bremenbankdb
    username: bremenbank_user
    password: bremen
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  file:
    name: log/bremenbank.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"

bremenbank:
  app:
    jwtSecret: bremenbank@@12
    jwtExpirationMs: 86400000